name: Validate Runners
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: [self-hosted,aws,runner]
    steps:
      - name: Runner Info
        run: |
          echo "Runner: $(hostname)"
          echo "Labels: $RUNNER_LABELS"